FROM ubuntu:24.04

# Instala apenas o necessário para RODAR o binário
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libudev-dev \
    ca-certificates \
    iputils-ping \
    net-tools \
    iproute2 \
    curl \
    python3 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app/config /app/db

# Comando padrão (segura o container vivo)
CMD ["/bin/bash"]